<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LT-SAKSHI" failures="1" tests="11" name="com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary" time="52.700" errors="0" timestamp="2024-07-25T17:59:29 IST" skipped="0">
  <testcase classname="com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary" name="Verify_Select_Entity" time="6.673"/>
  <testcase classname="com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary" name="Verify_Select_Product" time="18.660"/>
  <testcase classname="com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary" name="Verify_ClickOn_PayoutsOption" time="1.280"/>
  <testcase classname="com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary" name="Verify_ClickOn_Bulk_BeneficiaryOption" time="0.644"/>
  <testcase classname="com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary" name="Verify_ClickOn_Add_Bulk_Beneficiary_Button" time="1.319"/>
  <testcase classname="com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary" name="writeDataToExcelFile" time="16.877"/>
  <testcase classname="com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary" name="Verify_Upload_ValidBeneficiaryFile" time="0.647"/>
  <testcase classname="com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary" name="Veirfy_SelectBankName" time="2.013"/>
  <testcase classname="com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary" name="Verify_EnterRemarkInField" time="0.783"/>
  <testcase classname="com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary" name="Verify_ClickOnConfirmButton" time="1.313"/>
  <testcase classname="com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary" name="Verify_InvalidStatus" time="2.491">
    <failure message="25175906&#039; is present on the page. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 25175906' is present on the page. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.TransBnk.Payouts.NegativeScenarios_BulkBeneficiary.Check_InvalidStatus(NegativeScenarios_BulkBeneficiary.java:361)
at com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary.Verify_InvalidStatus(TestClass_NegativeScenarios_BulkBeneficiary.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verify_InvalidStatus -->
</testsuite> <!-- com.TransBnk.TestClass_Payouts.TestClass_NegativeScenarios_BulkBeneficiary -->
